channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - pandas
  - pip:
    - xmltodict
    - requests
    - requests_cache
    - tqdm
    - pyteomics
    - lxml
    - rdkit
    - numpy
